# Generated by Django 5.0.6 on 2026-05-01 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('subject', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Franchise Request', 'Franchise Request'), ('Investment Interest', 'Investment Interest'), ('Feedback', 'Feedback')], default='General Inquiry', max_length=50, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Replied')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted On')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('investment_range', models.CharField(blank=True, choices=[('10-25 Lakhs', '10-25 Lakhs'), ('25-50 Lakhs', '25-50 Lakhs'), ('50 Lakhs - 1 Crore', '50 Lakhs - 1 Crore'), ('1 Crore+', '1 Crore+')], max_length=50, null=True, verbose_name='Expected Investment Range')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Additional Remarks')),
                ('consent', models.BooleanField(default=True, verbose_name='Consent Given')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted On')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Contacted')),
            ],
            options={
                'verbose_name': 'Franchise Request',
                'verbose_name_plural': 'Franchise Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200, verbose_name='Reviewer Name')),
                ('reviewer_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Rating')),
                ('review_message', models.TextField(verbose_name='Review Message')),
                ('consent', models.BooleanField(default=True, verbose_name='Consent Given')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved for Display')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted On')),
            ],
            options={
                'verbose_name': 'Rating & Review',
                'verbose_name_plural': 'Ratings & Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
